// ─── BigO Lens — Complexity Report Command ───────────────────
//
// Generates a markdown complexity report for functions in the
// current file or entire workspace.

import * as vscode from 'vscode';
import { analyzeFile } from '../core/analyzer';
import { getPatternLabel } from '../core/patterns';
import { getSeverity, ComplexityResult, COMPLEXITY_WEIGHT } from '../core/types';

export async function exportComplexityReport(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage('BigO Lens: Open a file to generate a report.');
    return;
  }

  const content = editor.document.getText();
  const filePath = editor.document.uri.fsPath;
  const fileName = filePath.split('/').pop() || filePath;

  const analysis = analyzeFile(content, filePath);

  if (analysis.functions.length === 0) {
    vscode.window.showInformationMessage('BigO Lens: No functions found in the current file.');
    return;
  }

  const report = buildReport(fileName, analysis.functions);

  // Open the report in a new untitled markdown document
  const doc = await vscode.workspace.openTextDocument({
    content: report,
    language: 'markdown',
  });
  await vscode.window.showTextDocument(doc, { preview: true });
}

function buildReport(fileName: string, functions: ComplexityResult[]): string {
  const now = new Date().toISOString().split('T')[0];
  const lines: string[] = [];

  lines.push(`# 📐 BigO Lens — Complexity Report`);
  lines.push('');
  lines.push(`**File:** \`${fileName}\``);
  lines.push(`**Date:** ${now}`);
  lines.push(`**Functions analyzed:** ${functions.length}`);
  lines.push('');

  // ── Summary table ──
  lines.push('## Summary');
  lines.push('');
  lines.push('| Function | Time | Space | Pattern | Confidence |');
  lines.push('|----------|------|-------|---------|------------|');

  for (const fn of functions) {
    const severity = getSeverity(fn.time);
    const icon = severity === 'good' ? '🟢' : severity === 'moderate' ? '🟡' : severity === 'warning' ? '🟠' : '🔴';
    const pattern = fn.patterns[0] !== 'unknown' ? fn.patterns[0] : '—';
    lines.push(`| ${icon} \`${fn.functionName}\` | \`${fn.time}\` | \`${fn.space}\` | ${pattern} | ${Math.round(fn.confidence * 100)}% |`);
  }
  lines.push('');

  // ── Detailed breakdown per function ──
  lines.push('## Detailed Analysis');
  lines.push('');

  for (const fn of functions) {
    const severity = getSeverity(fn.time);
    const icon = severity === 'good' ? '🟢' : severity === 'moderate' ? '🟡' : severity === 'warning' ? '🟠' : '🔴';

    lines.push(`### ${icon} \`${fn.functionName}\` (lines ${fn.startLine}–${fn.endLine})`);
    lines.push('');
    lines.push(`- **Time:** \`${fn.time}\``);
    lines.push(`- **Space:** \`${fn.space}\``);
    lines.push(`- **Confidence:** ${Math.round(fn.confidence * 100)}%`);
    lines.push('');

    // Patterns
    if (fn.patterns.length > 0 && fn.patterns[0] !== 'unknown') {
      lines.push('**Patterns:**');
      for (const p of fn.patterns) {
        lines.push(`- ${getPatternLabel(p)}`);
      }
      lines.push('');
    }

    // Analysis breakdown
    if (fn.explanation.length > 0) {
      lines.push('**Analysis:**');
      for (const exp of fn.explanation) {
        lines.push(`- ${exp}`);
      }
      lines.push('');
    }

    // Optimization hints
    if (fn.optimizations.length > 0) {
      lines.push('**Optimization Suggestions:**');
      for (const opt of fn.optimizations) {
        lines.push(`- 💡 **${opt.technique}**: ${opt.message}`);
        lines.push(`  - \`${opt.currentComplexity}\` → \`${opt.suggestedComplexity}\``);
      }
      lines.push('');
    }

    // LeetCode info
    if (fn.leetcode) {
      lines.push(`**LeetCode:** [#${fn.leetcode.number} — ${fn.leetcode.name}](${fn.leetcode.url})`);
      if (fn.leetcode.optimalTime) {
        const match = fn.time === fn.leetcode.optimalTime;
        lines.push(`- Optimal time: \`${fn.leetcode.optimalTime}\` ${match ? '✅' : '⚠️'}`);
      }
      if (fn.leetcode.optimalSpace) {
        const match = fn.space === fn.leetcode.optimalSpace;
        lines.push(`- Optimal space: \`${fn.leetcode.optimalSpace}\` ${match ? '✅' : '⚠️'}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // ── Footer ──
  lines.push('');
  lines.push('> Generated by [BigO Lens](https://marketplace.visualstudio.com/items?itemName=YTTHEMIGHTY.bigo-lens) — Pure AST analysis, no AI.');

  return lines.join('\n');
}
